// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/agg-logo/SimplifiedAG.tsx": () => import("../components/mockups/agg-logo/SimplifiedAG.tsx"),
  "./components/mockups/agg-logo/WindshieldGrowth.tsx": () => import("../components/mockups/agg-logo/WindshieldGrowth.tsx"),
  "./components/mockups/agg-logo/WordmarkFirst.tsx": () => import("../components/mockups/agg-logo/WordmarkFirst.tsx")
};
